# Generated by Django 3.1.3 on 2020-11-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowtask', '0002_auto_20201108_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='create_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
    ]
