# Generated by Django 3.1.3 on 2020-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowtask', '0003_auto_20201108_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
